### ISSUE TITLE
Issue when webui logging is false

### ISSUE THREAD

**Issue by farski** [tphakala/birdnet-go#35]
Any time I set webserver logging to `false` I get some errors when loading the UI. The page still partially loads, but it's broken.

```
BirdNET GLOBAL 6K V2.4 FP32 model initialized, using 4 threads of available 4 CPUs
Starting BirdNET-Go Analyzer in realtime mode
Threshold: 0.8, sensitivity: 1, interval: 15
Logging disabled
⇨ http server started on [::]:8080
Listening ...
echo: http: panic serving [fe80::823:50f4:1d31:1884%wlan0]:55092: runtime error: invalid memory address or nil pointer dereference
goroutine 51 [running]:
net/http.(*conn).serve.func1()
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:1868 +0xb0
panic({0xc18b00?, 0x12367c0?})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/runtime/panic.go:920 +0x26c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).log(0x0, {0xcc9c4e, 0x3}, 0x0, {0xcd2ab7?, 0x20?}, {0x400019f738?, 0x40000ba0c1?, 0x400019f788?})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:157 +0x8c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).Info(...)
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:133
github.com/tphakala/birdnet-go/internal/httpcontroller.(*Server).setupCustomLogger.func1({_, _}, {{0xc16cf324375557d0, 0x97f1a7db, 0x54c0ce0}, 0x0, {0x0, 0x0}, {0x40000ba0c1, 0x1e}, ...})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/httpcontroller/init.go:120 +0xf4
github.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1({0xe17138, 0x4000124000})
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/middleware/request_logger.go:378 +0x6ac
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x40001ec480, {0xe0c9f0?, 0x4000108000}, 0x40002a0000)
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/echo.go:669 +0x374
net/http.serverHandler.ServeHTTP({0x4000218210?}, {0xe0c9f0?, 0x4000108000?}, 0x6?)
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x40000f8240, {0xe0e208, 0x40002181b0})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 24
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:3086 +0x4cc
echo: http: panic serving [fe80::823:50f4:1d31:1884%wlan0]:55095: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1()
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:1868 +0xb0
panic({0xc18b00?, 0x12367c0?})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/runtime/panic.go:920 +0x26c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).log(0x0, {0xcc9c4e, 0x3}, 0x0, {0xcd2ab7?, 0x20?}, {0x4000985738?, 0x4000307b61?, 0x4000985788?})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:157 +0x8c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).Info(...)
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:133
github.com/tphakala/birdnet-go/internal/httpcontroller.(*Server).setupCustomLogger.func1({_, _}, {{0xc16cf32443bb8ec8, 0x9ff2a8d2, 0x54c0ce0}, 0x0, {0x0, 0x0}, {0x4000307b61, 0x1e}, ...})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/httpcontroller/init.go:120 +0xf4
github.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1({0xe17138, 0x40000a6320})
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/middleware/request_logger.go:378 +0x6ac
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x40001ec480, {0xe0c9f0?, 0x4000272000}, 0x40001e6d00)
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/echo.go:669 +0x374
net/http.serverHandler.ServeHTTP({0x40001f13e0?}, {0xe0c9f0?, 0x4000272000?}, 0x6?)
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x40002a2240, {0xe0e208, 0x40002181b0})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 24
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:3086 +0x4cc
echo: http: panic serving [fe80::823:50f4:1d31:1884%wlan0]:55094: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1()
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:1868 +0xb0
panic({0xc18b00?, 0x12367c0?})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/runtime/panic.go:920 +0x26c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).log(0x0, {0xcc9c4e, 0x3}, 0x0, {0xcd2ab7?, 0x20?}, {0x4000341738?, 0x400071c0c1?, 0x4000341788?})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:157 +0x8c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).Info(...)
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:133
github.com/tphakala/birdnet-go/internal/httpcontroller.(*Server).setupCustomLogger.func1({_, _}, {{0xc16cf32443ba07ac, 0x9ff121c9, 0x54c0ce0}, 0x0, {0x0, 0x0}, {0x400071c0c1, 0x1e}, ...})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/httpcontroller/init.go:120 +0xf4
github.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1({0xe17138, 0x400012e0a0})
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/middleware/request_logger.go:378 +0x6ac
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x40001ec480, {0xe0c9f0?, 0x4000882000}, 0x40003ae600)
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/echo.go:669 +0x374
net/http.serverHandler.ServeHTTP({0x400024c2d0?}, {0xe0c9f0?, 0x4000882000?}, 0x6?)
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x40002a21b0, {0xe0e208, 0x40002181b0})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 24
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:3086 +0x4cc
echo: http: panic serving [fe80::823:50f4:1d31:1884%wlan0]:55096: runtime error: invalid memory address or nil pointer dereference
goroutine 5 [running]:
net/http.(*conn).serve.func1()
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:1868 +0xb0
panic({0xc18b00?, 0x12367c0?})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/runtime/panic.go:920 +0x26c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).log(0x0, {0xcc9c4e, 0x3}, 0x0, {0xcd2ab7?, 0x20?}, {0x4000981738?, 0x4000307b31?, 0x4000981788?})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:157 +0x8c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).Info(...)
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:133
github.com/tphakala/birdnet-go/internal/httpcontroller.(*Server).setupCustomLogger.func1({_, _}, {{0xc16cf32443bf128a, 0x9ff62cf1, 0x54c0ce0}, 0x0, {0x0, 0x0}, {0x4000307b31, 0x1e}, ...})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/httpcontroller/init.go:120 +0xf4
github.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1({0xe17138, 0x40002128c0})
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/middleware/request_logger.go:378 +0x6ac
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x40001ec480, {0xe0c9f0?, 0x4000150000}, 0x40001e6c00)
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/echo.go:669 +0x374
net/http.serverHandler.ServeHTTP({0x40001f12c0?}, {0xe0c9f0?, 0x4000150000?}, 0x6?)
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x40002a2120, {0xe0e208, 0x40002181b0})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 24
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:3086 +0x4cc
echo: http: panic serving [fe80::823:50f4:1d31:1884%wlan0]:55097: runtime error: invalid memory address or nil pointer dereference
goroutine 48 [running]:
net/http.(*conn).serve.func1()
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:1868 +0xb0
panic({0xc18b00?, 0x12367c0?})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/runtime/panic.go:920 +0x26c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).log(0x0, {0xcc9c4e, 0x3}, 0x0, {0xcd2ab7?, 0x20?}, {0x4000985738?, 0x40000ba0f1?, 0x4000985788?})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:157 +0x8c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).Info(...)
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:133
github.com/tphakala/birdnet-go/internal/httpcontroller.(*Server).setupCustomLogger.func1({_, _}, {{0xc16cf32449135e40, 0xa54a7838, 0x54c0ce0}, 0x0, {0x0, 0x0}, {0x40000ba0f1, 0x1e}, ...})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/httpcontroller/init.go:120 +0xf4
github.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1({0xe17138, 0x40002120a0})
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/middleware/request_logger.go:378 +0x6ac
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x40001ec480, {0xe0c9f0?, 0x40001081c0}, 0x40002a0100)
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/echo.go:669 +0x374
net/http.serverHandler.ServeHTTP({0x40009d2030?}, {0xe0c9f0?, 0x40001081c0?}, 0x6?)
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x40002a2090, {0xe0e208, 0x40002181b0})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 24
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:3086 +0x4cc
echo: http: panic serving [fe80::823:50f4:1d31:1884%wlan0]:55098: runtime error: invalid memory address or nil pointer dereference
goroutine 55 [running]:
net/http.(*conn).serve.func1()
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:1868 +0xb0
panic({0xc18b00?, 0x12367c0?})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/runtime/panic.go:920 +0x26c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).log(0x0, {0xcc9c4e, 0x3}, 0x0, {0xcd2ab7?, 0x20?}, {0x4000985738?, 0x40000ba121?, 0x4000985788?})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:157 +0x8c
github.com/tphakala/birdnet-go/internal/logger.(*Logger).Info(...)
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/logger/logger.go:133
github.com/tphakala/birdnet-go/internal/httpcontroller.(*Server).setupCustomLogger.func1({_, _}, {{0xc16cf3244e0df848, 0xaa451265, 0x54c0ce0}, 0x0, {0x0, 0x0}, {0x40000ba121, 0x1e}, ...})
	/home/thakala/go/src/github.com/tphakala/birdnet-go/internal/httpcontroller/init.go:120 +0xf4
github.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1({0xe17138, 0x4000212140})
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/middleware/request_logger.go:378 +0x6ac
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x40001ec480, {0xe0c9f0?, 0x40001082a0}, 0x40002a0200)
	/home/thakala/go/pkg/mod/github.com/labstack/echo/v4@v4.11.4/echo.go:669 +0x374
net/http.serverHandler.ServeHTTP({0x40009d21e0?}, {0xe0c9f0?, 0x40001082a0?}, 0x6?)
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x40001f6240, {0xe0e208, 0x40002181b0})
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 24
	/home/thakala/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.6.linux-arm64/src/net/http/server.go:3086 +0x4cc
```

**Comment by tphakala** [comment]
thanks for reporting, issue is now fixed
